### ISSUE TITLE
unauthorised error when connecting to nis on docker

### ISSUE THREAD

**Issue by HaoCHEN3** [rb2nem/nem-docker#8]
unauthorised error(code 401). I ran nis on docker based on the guide. when i connects to the nis, i got the authorised error. How to solve it.

**Comment by lezhnev74** [comment]
I have the same issue.
I run container and I have port 7890 exposed. 
I can request public data like this:
```
> curl -XGET 127.0.0.1:7890/status
{"code":5,"type":4,"message":"status"}
```

But if I want to generate a new account I get an error:
```
> curl -XGET 127.0.0.1:7890/account/generate
{"timeStamp":86880338,"error":"Unauthorized","message":"remote 172.17.0.1 attempted to call local \/account\/generate","status":401}
```


I believe this has something to do wit hdocker image configuration. Can you advise how to solve this one?

**Comment by rb2nem** [comment]
This is because you call this URL `/account/generate` remotely, and for security reason this URL can only be requested locally. You send your request to 127.0.0.1, but it is in reality redirected to the docker container's IP address. You can see the IP address seen by NIS is 172.17.0.1. So NIS doesn't see this as a local request, and refuses to answer to that particular request because it would send the private key of an account over the network.
If you need to get this request handled, you need to log into the nis container using the ndev script like this:
```
./ndev -c nis bash
curl -XGET 127.0.0.1:7890/account/generate
```

**Comment by ghost** [comment]
@rb2nem Where is the ndev script located? IS that on a develop branch for NEM?

**Comment by rb2nem** [comment]
The `ndev` script is from the dev guide, and is at https://github.com/rb2nem/nem-dev-guide/blob/master/docker/ndev
The original question mentioned the guide, hene the mention of ndev. If you run a container with nis, you need to execute the command in the container itself, with `docker exec`.
